title: Karen Atkinson
#logo: (relative path of photo, starts with / ... not enclosed by brackets)
description: Data Scientist / Data Analyst
"[Tableau Public Visuals](https://public.tableau.com/app/profile/karen.atkinson.2000)"
show_downloads: False
theme: jekyll-theme-minimal
