title: Karen Atkinson
#logo: (relative path of photo, starts with / ... not enclosed by brackets)
description: Data Scientist / Data Analyst
description: <a ref="https://public.tableau.com/app/profile/karen.atkinson.2000"> Tableau Public Visuals</a>
show_downloads: False
theme: jekyll-theme-minimal
